[phases.setup]
nixPkgs = ["...", "bun"]

[phases.install]
# Installs all dependencies from the monorepo root
cmds = ["bun install"]

[phases.build]
# Filters to build only the "@season-summary/app" package
cmds = ["bun run --filter @season-summary/app build"]

[start]
# Changes directory before starting the server
cmd = "cd app && bun --bun src/index.js"
