[phases.setup]
# This tells Nixpacks to install the Bun package into the environment
nixPkgs = ["...", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"
